contact_links:
  - name: 📃 Auth backend Issue
    url: https://github.com/Wanclouds/identity-provider-BE/issues/new
    about: This issue tracker is not for backend issues. Please file auth backend issues here.
  - name: 🤔 Questions and Help
    url: https://reactjs.org/community/support.html
    about: This issue tracker is not for support questions. Please refer to the React community's help and discussion forums.
