# .github/workflows/label-prs.yml
name: Label PRs with Approvals

on:
  pull_request_review:
    types: [submitted]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR approvals
        id: check
        run: |
          approvals=$(gh api repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}/reviews | jq '[.[] | select(.state == "APPROVED")] | length')
          echo "::set-output name=approvals::$approvals"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Label PR if approvals >= 2
        if: steps.check.outputs.approvals >= 2
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "2+ Approvals"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
